name: Bootstrap Workflow

env:
  TOOLS_BRANCH: dev

on:
  workflow_call:
    secrets:
      token: 
        description: 'Secret token from caller workflow to approve readme'
        required: true

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" | tee -a $GITHUB_STEP_SUMMARY

  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: checkout-actions
        uses: actions/checkout@v4
        with:
          repository: 'fiddlermikey/project-repo'
          path: './actions/'
          token: ${{ secrets.token }}
          ref: ${{ github.ref_name }} # Update this tag for testing new readme templates branches
      - name: Output Context Info
        run: |
          echo "github.action_ref: ${{ github.action_ref }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "github.ref_name: ${{ github.ref_name }}" | tee -a $GITHUB_STEP_SUMMARY
