name: Passing Outputs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  get-release-values:
    name: Get Release Properties
    runs-on: ubuntu-latest
    outputs:
      PUSH_IMAGE: ${{ steps.get-is-release.outputs.PUSH_IMAGE }}  
    steps:
      - name: get-is-release
        run: |
          echo "PUSH_IMAGE=true" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT  | tee -a $GITHUB_STEP_SUMMARY
      - name: output-output
        run: |
          echo "GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
  merge:
    runs-on: ubuntu-latest
    needs: get-release-values
    steps:
      - name: Check PUSH_IMAGE value
        run: |
          echo "PUSH_IMAGE = ${{ needs.get-release-values.outputs.PUSH_IMAGE }}"

