name: Passing Outputs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  get-release-values:
    name: Get Release Properties
    runs-on: ubuntu-latest
    outputs:
      PUSH_IMAGE: ${{ needs.set-vars.outputs.PUSH_IMAGE }}
    steps:
      - name: Set PUSH_IMAGE variable
        id: set-vars
        run: |
          echo "PUSH_IMAGE=true" >> $GITHUB_ENV
          echo "PUSH_IMAGE=${{ github.event.inputs.PUSH_IMAGE }}" >> $GITHUB_OUTPUTS
        # Additional steps if needed

  merge:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Check PUSH_IMAGE value
        run: |
          echo "PUSH_IMAGE = ${{ needs.set-vars.outputs.PUSH_IMAGE }}"
