name: Bootstrap Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

env:
  REGISTRY: ghcr.io

jobs:
  get-release-values:
    name: Get Release Properties
    runs-on: ubuntu-latest
    outputs:
      PUSH_IMAGE: ${{ steps.get-is-release.outputs.PUSH_IMAGE }}  
    steps:
      - name: get-is-release
        run: |
          echo "PUSH_IMAGE=true" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT  | tee -a $GITHUB_STEP_SUMMARY
          echo "VERSION=1.1.0" | tee -a $GITHUB_ENV  | tee -a $GITHUB_OUTPUT | tee -a $GITHUB_STEP_SUMMARY
  merge:
    runs-on: ubuntu-latest
    needs: get-release-values
    steps:
      - name: Set IMAGE_NAME
        run: |
          echo "PUSH_IMAGE = ${{ needs.get-release-values.outputs.PUSH_IMAGE }}"

