name: Passing Outputs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  get-release-values:
    name: Get Release Properties
    runs-on: ubuntu-latest
    outputs:
      PUSH_IMAGE: ${{ needs.set-vars.outputs.PUSH_IMAGE }}
    steps:
      - name: Set PUSH_IMAGE variable
        id: set-vars
        run: |
          echo "PUSH_IMAGE=true" >> "$GITHUB_OUTPUT"

  merge:
    runs-on: ubuntu-latest
    needs: get-release-values
    steps:
      - env:
          PUSH_IMAGE: ${{needs.get-release-values.outputs.PUSH_IMAGE}}
        name: Check PUSH_IMAGE value
        run: |
          echo "PUSH_IMAGE = $PUSH_IMAGE"

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output_1: ${{ steps.step1.outputs.test }}
      PUSH_IMAGE: ${{ steps.step2.outputs.PUSH_IMAGE }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "PUSH_IMAGE=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output_1}}
          PUSH_IMAGE: ${{needs.job1.outputs.PUSH_IMAGE}}
        run: echo "$OUTPUT1 $PUSH_IMAGE"
