name: Matrix test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  get-release-values:
    name: Get Release Properties
    runs-on: ubuntu-latest
    outputs:
      PUSH_IMAGE: ${{ steps.set-vars.outputs.PUSH_IMAGE }}
    steps:
      - name: set-vars
        run: |
          echo "PUSH_IMAGE=true" |tee -a "$GITHUB_OUTPUT" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "VERSION=0.0.0" | tee -a "$GITHUB_OUTPUT" | tee -a "$GITHUB_STEP_SUMMARY"

  matrix-test:
    runs-on: ubuntu-latest
    needs: get-release-values
    steps:
      - name: Check PUSH_IMAGE value
        run: |
          echo "PUSH_IMAGE = ${{needs.get-release-values.outputs.PUSH_IMAGE}}"
