name: Bootstrap Workflow


on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, synchronize]
  push:

jobs:
  call-generate-readme-workflow:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: fiddlermikey/project-repo/.github/workflows/called-workflow.yml@pass-branch
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
